In [14]:
import pandas as pd
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
import numpy as np

In [15]:
df = pd.read_csv("example_131.csv",delimiter=",",names = ['label','message']) #Loading the data from example 13.1
df2 = pd.read_csv("example_1310.csv",delimiter=",",names = ['label','message']) #Loading the data from example 13.10
df3 = pd.read_csv("example_spam.csv",delimiter=",",names = ['label','message']) #Loading the data from example spam detection

In [16]:
values,values2,values3 = df.get_values(),df2.get_values(),df3.get_values()

In [17]:
values = df.get_values()
print("Values for the example 13.1")
print(values.shape)
print(values)
print("\n Values for the example 13.10")
print(values2.shape)
print(values2)
print("\n Values for the example spam detection")
print(values3.shape)
print(values3)

Values for the example 13.1
(5, 2)
[['China' 'Chinese Beijing Chinese']
 ['China' 'Chinese Chinese Shanghai']
 ['China' 'Chinese Macao']
 ['Not China' 'Tokyo Japan Chinese']
 ['?' 'Chinese Chinese Chinese Tokyo Japan']]

 Values for the example 13.10
(5, 2)
[['China' 'Taipei Taiwan']
 ['China' 'Macao Taiwan Shanghai']
 ['Not China' 'Japan Sapporo']
 ['Not China' 'Sapporo Osaka Taiwan']
 ['?' 'Taiwan Taiwan Sapporo']]

 Values for the example spam detection
(7, 2)
[['spam' 'send us your password']
 ['ham' 'send us your review']
 ['ham' 'review your password']
 ['spam' 'review us']
 ['spam' 'send your password']
 ['spam' 'send us your password']
 ['?' 'review us now']]


In [18]:
df['message'] = df['message'].str.lower()
df2['message'] = df2['message'].str.lower()
df3['message'] = df3['message'].str.lower()

In [19]:
import nltk

In [20]:
df['message'] = df['message'].apply(nltk.word_tokenize)
df2['message'] = df2['message'].apply(nltk.word_tokenize)
df3['message'] = df3['message'].apply(nltk.word_tokenize)
print("\n Messages after tokenization for the example 13.10")
print(df['message'])
print("\n Messages after tokenization for the example 13.1")
print(df2['message'])
print("\n Messages after tokenization for the example spam detection")
print(df3['message'])


 Messages after tokenization for the example 13.10
0                  [chinese, beijing, chinese]
1                 [chinese, chinese, shanghai]
2                             [chinese, macao]
3                      [tokyo, japan, chinese]
4    [chinese, chinese, chinese, tokyo, japan]
Name: message, dtype: object

 Messages after tokenization for the example 13.1
0             [taipei, taiwan]
1    [macao, taiwan, shanghai]
2             [japan, sapporo]
3     [sapporo, osaka, taiwan]
4    [taiwan, taiwan, sapporo]
Name: message, dtype: object

 Messages after tokenization for the example spam detection
0    [send, us, your, password]
1      [send, us, your, review]
2      [review, your, password]
3                  [review, us]
4        [send, your, password]
5    [send, us, your, password]
6             [review, us, now]
Name: message, dtype: object


In [21]:
stemmer = PorterStemmer()
df['message'] = df['message'].apply(lambda x: [stemmer.stem(y) for y in x])
df2['message'] = df2['message'].apply(lambda x: [stemmer.stem(y) for y in x])
df3['message'] = df3['message'].apply(lambda x: [stemmer.stem(y) for y in x])

In [22]:
df['message'] = df['message'].apply(lambda x: ' '.join(x))
df2['message'] = df2['message'].apply(lambda x: ' '.join(x))
df3['message'] = df3['message'].apply(lambda x: ' '.join(x))
count_vect = CountVectorizer()

print("Counts and messages for the example 13.1")
counts = count_vect.fit_transform(df['message'])
print(count_vect.get_feature_names())
print(counts.toarray())
print(df['message'])

print("\n Counts and messages for the example 13.10")
counts2 = count_vect.fit_transform(df2['message'])
print(count_vect.get_feature_names())
print(counts2.toarray())
print(df2['message'])

print("\n Counts and messages for the example spam detection")
counts3 = count_vect.fit_transform(df3['message'])
print(count_vect.get_feature_names())
print(counts3.toarray())
print(df3['message'])

Counts and messages for the example 13.1
['beij', 'chines', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]
 [0 3 1 0 0 1]]
0                  chines beij chines
1              chines chines shanghai
2                        chines macao
3                  tokyo japan chines
4    chines chines chines tokyo japan
Name: message, dtype: object

 Counts and messages for the example 13.10
['japan', 'macao', 'osaka', 'sapporo', 'shanghai', 'taipei', 'taiwan']
[[0 0 0 0 0 1 1]
 [0 1 0 0 1 0 1]
 [1 0 0 1 0 0 0]
 [0 0 1 1 0 0 1]
 [0 0 0 1 0 0 2]]
0            taipei taiwan
1    macao taiwan shanghai
2            japan sapporo
3     sapporo osaka taiwan
4    taiwan taiwan sapporo
Name: message, dtype: object

 Counts and messages for the example spam detection
['now', 'password', 'review', 'send', 'us', 'your']
[[0 1 0 1 1 1]
 [0 0 1 1 1 1]
 [0 1 1 0 0 1]
 [0 0 1 0 1 0]
 [0 1 0 1 0 1]
 [0 1 0 1 1 1]
 [1 0 1 0 1 0]]
0    send us your password
1  

In [23]:
transformer = TfidfTransformer().fit(counts)
counts = transformer.transform(counts)
transformer2 = TfidfTransformer().fit(counts2)
counts2 = transformer2.transform(counts2)
transformer3 = TfidfTransformer().fit(counts3)
counts3 = transformer3.transform(counts3)

In [24]:
#x_train, x_test, y_train, y_test = train_test_split(counts, df['label'], test_size=.1)
x_train = counts[:4]
x_test = counts[4:5]
y_train = pd.Series(df.get_values()[0:4][:,0])
y_test = pd.Series(df.get_values()[4:5][:,0])

x_train2 = counts2[:4]
x_test2 = counts2[4:5]
y_train2 = pd.Series(df2.get_values()[0:4][:,0])
y_test2 = pd.Series(df2.get_values()[4:5][:,0])

x_train3 = counts3[:6]
x_test3 = counts3[6:7]
y_train3 = pd.Series(df3.get_values()[0:6][:,0])
y_test3 = pd.Series(df3.get_values()[6:7][:,0])

In [25]:
model = MultinomialNB()

In [26]:
model.fit(x_train, y_train)
predicted = model.predict(x_test)
print("Results for the example 13.1. The sample is \"" + str(df['message'][4])+ "\"")
print("Predicted class: " + str(predicted))
print("Probabilities for each class: " + str(model.predict_proba(x_test)))

model.fit(x_train2, y_train2)
predicted2 = model.predict(x_test2)
print("\n Results for the example 13.10. The sample is \"" + str(df2['message'][4])+ "\"")
print("Predicted class: " + str(predicted2))
print("Probabilities for each class: " + str(model.predict_proba(x_test2)))

model.fit(x_train3, y_train3)
predicted3 = model.predict(x_test3)
print("\n Results for the example spam detection. The sample is \"" + str(df3['message'][6]) + "\"")
print("Predicted class: " + str(predicted3))
print("Probabilities for each class: " + str(model.predict_proba(x_test3)))

Results for the example 13.1. The sample is "chines chines chines tokyo japan"
Predicted class: ['China']
Probabilities for each class: [[0.67804117 0.32195883]]

 Results for the example 13.10. The sample is "taiwan taiwan sapporo"
Predicted class: ['Not China']
Probabilities for each class: [[0.46597316 0.53402684]]

 Results for the example spam detection. The sample is "review us now"
Predicted class: ['spam']
Probabilities for each class: [[0.41671911 0.58328089]]
