In [13]:
import pandas as pd
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix
import numpy as np

In [14]:
df = pd.read_csv("example_131.csv",delimiter=",",names = ['label','message']) #Loading the data from example 13.1
df2 = pd.read_csv("example_1310.csv",delimiter=",",names = ['label','message']) #Loading the data from example 13.10
df3 = pd.read_csv("example_spam.csv",delimiter=",",names = ['label','message']) #Loading the data from example spam detection

In [15]:
values,values2,values3 = df.get_values(),df2.get_values(),df3.get_values()

In [16]:
values = df.get_values()

In [17]:
df['message'] = df['message'].str.lower()
df2['message'] = df2['message'].str.lower()
df3['message'] = df3['message'].str.lower()

In [18]:
import nltk

In [19]:
df['message'] = df['message'].apply(nltk.word_tokenize)
df2['message'] = df2['message'].apply(nltk.word_tokenize)
df3['message'] = df3['message'].apply(nltk.word_tokenize)

In [20]:
stemmer = PorterStemmer()
df['message'] = df['message'].apply(lambda x: [stemmer.stem(y) for y in x])
df2['message'] = df2['message'].apply(lambda x: [stemmer.stem(y) for y in x])
df3['message'] = df3['message'].apply(lambda x: [stemmer.stem(y) for y in x])

In [21]:
df['message'] = df['message'].apply(lambda x: ' '.join(x))
df2['message'] = df2['message'].apply(lambda x: ' '.join(x))
df3['message'] = df3['message'].apply(lambda x: ' '.join(x))
count_vect = CountVectorizer()

In [22]:
print("Counts and messages for the example 13.1")
counts = count_vect.fit_transform(df['message'])
print(count_vect.get_feature_names())
print(counts.toarray())
print(df['message'])

print("\n Counts and messages for the example 13.10")
counts2 = count_vect.fit_transform(df2['message'])
print(count_vect.get_feature_names())
print(counts2.toarray())
print(df2['message'])

print("\n Counts and messages for the example spam detection")
counts3 = count_vect.fit_transform(df3['message'])
print(count_vect.get_feature_names())
print(counts3.toarray())
print(df3['message'])

transformer = TfidfTransformer().fit(counts)
counts = transformer.transform(counts)
transformer2 = TfidfTransformer().fit(counts2)
counts2 = transformer2.transform(counts2)
transformer3 = TfidfTransformer().fit(counts3)
counts3 = transformer3.transform(counts3)

Counts and messages for the example 13.1
['beij', 'chines', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]
 [0 3 1 0 0 1]]
0                  chines beij chines
1              chines chines shanghai
2                        chines macao
3                  tokyo japan chines
4    chines chines chines tokyo japan
Name: message, dtype: object

 Counts and messages for the example 13.10
['japan', 'macao', 'osaka', 'sapporo', 'shanghai', 'taipei', 'taiwan']
[[0 0 0 0 0 1 1]
 [0 1 0 0 1 0 1]
 [1 0 0 1 0 0 0]
 [0 0 1 1 0 0 1]
 [0 0 0 1 0 0 2]]
0            taipei taiwan
1    macao taiwan shanghai
2            japan sapporo
3     sapporo osaka taiwan
4    taiwan taiwan sapporo
Name: message, dtype: object

 Counts and messages for the example spam detection
['now', 'password', 'review', 'send', 'us', 'your']
[[0 1 0 1 1 1]
 [0 0 1 1 1 1]
 [0 1 1 0 0 1]
 [0 0 1 0 1 0]
 [0 1 0 1 0 1]
 [0 1 0 1 1 1]
 [1 0 1 0 1 0]]
0    send us your password
1  

In [23]:
transformer = TfidfTransformer().fit(counts)
counts = transformer.transform(counts)
transformer2 = TfidfTransformer().fit(counts2)
counts2 = transformer2.transform(counts2)
transformer3 = TfidfTransformer().fit(counts3)
counts3 = transformer3.transform(counts3)

In [24]:
x_train = counts[:4]
x_test = counts[4:5]
y_train = pd.Series(df.get_values()[0:4][:,0])
y_test = pd.Series(df.get_values()[4:5][:,0])

x_train2 = counts2[:4]
x_test2 = counts2[4:5]
y_train2 = pd.Series(df2.get_values()[0:4][:,0])
y_test2 = pd.Series(df2.get_values()[4:5][:,0])

x_train3 = counts3[:6]
x_test3 = counts3[6:7]
y_train3 = pd.Series(df3.get_values()[0:6][:,0])
y_test3 = pd.Series(df3.get_values()[6:7][:,0])

In [25]:
model = BernoulliNB()

In [26]:
model.fit(x_train, y_train)
predicted = model.predict(x_test)
print("Results for the example 13.1. The sample is \"" + str(df['message'][4])+ "\"")
print("Predicted class: " + str(predicted))
print("Probabilities for each class: " + str(model.predict_proba(x_test)))

model.fit(x_train2, y_train2)
predicted2 = model.predict(x_test2)
print("\n Results for the example 13.10. The sample is \"" + str(df2['message'][4])+ "\"")
print("Predicted class: " + str(predicted2))
print("Probabilities for each class: " + str(model.predict_proba(x_test2)))

model.fit(x_train3, y_train3)
predicted3 = model.predict(x_test3)
print("\n Results for the example spam detection. The sample is \"" + str(df3['message'][6]) + "\"")
print("Predicted class: " + str(predicted3))
print("Probabilities for each class: " + str(model.predict_proba(x_test3)))

Results for the example 13.1. The sample is "chines chines chines tokyo japan"
Predicted class: ['Not China']
Probabilities for each class: [[0.19106679 0.80893321]]

 Results for the example 13.10. The sample is "taiwan taiwan sapporo"
Predicted class: ['Not China']
Probabilities for each class: [[0.25 0.75]]

 Results for the example spam detection. The sample is "review us now"
Predicted class: ['ham']
Probabilities for each class: [[0.68109623 0.31890377]]
